### ISSUE TITLE
Travis build fails due to timeout issue

### ISSUE THREAD

**Issue by SridharJagannathan** [natverse/elmr#48]
The travis build fails due to timeout issue, please check: https://travis-ci.org/natverse/elmr/jobs/620142341

Possibly consider splitting the builds so that the caches are already pre-loaded.

**Comment by SridharJagannathan** [comment]
@jefferis thanks for your comments, I think I have fixed the issue for now, you can see the solution here: https://github.com/natverse/elmr/blob/master/.travis.yml
I tested this with the following:
1) Clear cache and run: 
   It produced run times of 44 mins (job_Cache: 38, job_test: 6 ) ![Screenshot 2019-12-08 at 13 28 15](https://user-images.githubusercontent.com/13106358/70390208-e2efc100-19c0-11ea-84f1-c461b64bd1cb.png)

2) Run after caching: 
It produced run times of 7 mins (job_Cache: 3, job_test: 4 ) ![Screenshot 2019-12-08 at 13 37 45](https://user-images.githubusercontent.com/13106358/70390216-ef741980-19c0-11ea-8cc3-66ba73082012.png)
As the time limit of 50 mins is only for a single job and not a build, we still have a buffer of 12 mins.
I wanted to make a PR and do this, but the travis builds would take a long time as they do one for a push and one for a PR, so I committed them on the main branch. 
Please close this once you think it is fixed.

**Comment by jefferis** [comment]
That’s great! Well done for figuring it out! I guess we will need to do this for quite a few builds. Do you think there is any room for simplification? Best, Greg.

**Comment by SridharJagannathan** [comment]
Hi @jefferis, I have already thought about making further simplifications (here is a 3-step cache), you can see the latest build (after clearing the cache) 
![Screenshot 2019-12-08 at 19 55 44](https://user-images.githubusercontent.com/13106358/70395252-c1103180-19f4-11ea-80b5-a5cb6fbf36cc.png)
Now, the max build time for a job now is about 20 mins (which is pretty far away from the 50 min limit), so I think we can employ a similar strategy for the other packages as well.

**Comment by jefferis** [comment]
Closed by @SridharJagannathan's work with an additional simplification in #49. Should now provide a general pattern for natverse builds.
