### ISSUE TITLE
FAFB  template for different resolution

### ISSUE THREAD

**Issue by albertplus007** [natverse/elmr#51]
Hi, nice library
Recently, i was processing FAFB dataset, and i saw the brain surface in this library, the original resolution for FAFB dataset is `4x4x40nm`, so i think if i have the skeletons of this resolution i can just map them together.
But i just wondering how to apply this template on other resolution, for example on `8x8x40nm`?How to change the template size to match it?
and should i change the coordinate of my skeletons datasets to match the FAFB template?
Sorry to bother you.

**Comment by jefferis** [comment]
Thank you. Please can you ask this question on the nat-user Google group.

https://groups.google.com/forum/m/#!forum/nat-user

**Comment by jefferis** [comment]
Closing as addressed here https://groups.google.com/forum/#!topic/nat-user/DDwLNMjv8i8
